name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.1

    - uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        tools: composer:v2
        extensions: pdo, sqlite

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: |
        composer config optimize-autoloader false
        composer install --prefer-dist --no-progress --no-scripts --no-ansi

    - name: Run tests
      run: ./vendor/bin/phpunit

    - name: Run static analysis
      run: ./vendor/bin/phpstan analyse --no-progress --error-format=github